# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f7042b8d511786b8780a9111b0f6da2c2e03efdeccfac48e38efdfe50d4c82b697d2d1de3cae79a0463df1d29c54d8dcda5afa8319e5fbfdb3f5ffff9ffbced

test:
  secret_key_base: 4fd4e27fa89dc7cc6a67b9d173dda3d5e7358378b3bb926acb9cc4096fc577f4018cb6eb7b2b113c65bd256be022364c63ff662a31daba78477e7e23c6c074cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
